
name: CiraosDynamicWorker

#! 热更新
# hotpatch:
#   - https://raw.githubusercontent.com/ChenYFan/ClientWorker/gh-pages/cw.js
#   #- https://cdn.jsdelivr.net/gh/ChenYFan/ClientWorker/cw.js
# hotpatch:
#   - https://raw.githubusercontent.com/ChenYFan/ClientWorker/gh-pages/config.yaml
#   #- https://cdn.jsdelivr.net/gh/ChenYFan/ClientWorker/config.yaml]

catch_rules:

  #! 纯静态网站加速
  # - rule: _ #ClientWorker语法糖，匹配当前域，返回一个域名带端口
  #     transform_rules: #转换规则，最上面的优先最高
  #       - search: \#.* #在发送请求时匹配#后内容并移除
  #         replace: ''
  #       - search: \?.* #在发送请求时匹配?后内容并移除，仅限静态请求
  #         replace: '' 
  #       - search: _ 
  #         replace: 
  #           - _ #保留原始请求
  #           - ciraos.github.io #GithubPage托管
  #           - ciraos.gitee.io #GiteePage托管
  #           # - unpkg.com/xxx-html@xxx.xxx/dist #NPM托管
  #           # - cdnjs.cloudflare.com/ajax/libs/xxx/xxx.xxx/dist #CDNJS托管（大雾
  #           # - examplebucket.oss-xx-xx.aliyuncs.com #阿里云对象存储托管
  #           # - xxx.tencentcs.com #腾讯对象存储托管
  #           # - xxx.qbox.me
  #       - search: \.html$
  #         header:
  #           Content-Type: text/html;charset=UTF-8 #修复标头
  #       - search: _
  #         action: fetch
  #         fetch:
  #           status: 200
  #           engine: classic
  #           preflight: false
  #           timeout: 5000

  #! ClientWorker语法糖，匹配当前域，返回一个域名带端口
  - rule: _
    transform_rules:
      - search: \#.+
        searchin: url
        replace: ''
      - search: _ 
        action: fetch
        fetch:
          engine: fetch 
      - search: (^4|^5) 
        searchin: status 
        action: return
        return:
          body: The GateWay is down!This Page is provided by ClientWorker!
          status: 503

  #! 并发CDN流量请求 - npm
  # - rule: ^https\:\/\/((cdn|fastly|gcore|test1|quantil)\.jsdelivr\.net\/npm|unpkg\.com)
  #   transform_rules:
  #     - search: _
  #       replace:
  #         - _
  #         - https://unpkg.zhimg.com
  #         - https://npm.elemecdn.com
  #         - https://code.bdstatic.com/npm
  #         #- https://npm.sourcegcdn.com
  #         #- https://cdn.bilicdn.tk/npm
  #       fetch:
  #         status: 200
  #         engine: parallel
  #         preflight: false

  #! 并发CDN流量请求 - cdnjs
  # - rule: ^https\:\/\/cdnjs\.cloudflare\.com\/ajax\/libs
  #   transform_rules:
  #     - search: _
  #       replace:
  #         - _
  #         - https://cdn.bootcdn.net/ajax/libs
  #         - https://lib.baomitu.com
  #         - https://mirrors.cqupt.edu.cn/cdnjs/ajax/libs
  #         - https://cdn.staticfile.org
  #         - https://mirrors.sustech.edu.cn/cdnjs/ajax/libs
  #         #- https://cdnjs.sourcegcdn.com/ajax/libs
  #       action: fetch
  #       fetch:
  #         status: 200
  #         engine: parallel
  #         preflight: false

  #! webp兼容计划 - jpg
  # - rule: (?<=^https\:\/\/s2.loli/(.*))\.jpg$
  #   transform_rules:
  #     - search: image\/webp
  #       searchin: header
  #       searchkey: Accept
  #       replace: .webp
  #       replacein: url
  #       replacekey: .jpg

  #! webp兼容计划 - png
  # - rule: (?<=^https\:\/\/s2.loli/(.*))\.png$
  #   transform_rules:
  #     - search: image\/webp
  #       searchin: header
  #       searchkey: Accept
  #       replace: .webp
  #       replacein: url
  #       replacekey: .jpg

  #! webp兼容计划 - gif
  # - rule: (?<=^https\:\/\/s2.loli/(.*))\.gif$
  #   transform_rules:
  #     - search: image\/webp
  #       searchin: header
  #       searchkey: Accept
  #       replace: .webp
  #       replacein: url
  #       replacekey: .jpg
