
name: CiraosDynamicWorker

#! 热更新
hotconfig:
  #- https://cdn.jsdelivr.net/gh/ChenYFan/ClientWorker/config.yaml
  - https://raw.githubusercontent.com/ChenYFan/ClientWorker/gh-pages/config.yaml

#! 自动清除过期缓存时间间隔
cleaninterval: 1000*60*4

catch_rules:

  #! ClientWorker语法糖，匹配当前域，返回一个域名带端口
  - rule: _
    transform_rules:
      - search: \#.+
        searchin: url
        replace: ''
      - search: _ 
        action: fetch
        fetch:
          engine: fetch
          status: 200
          preflight: false
          timeout: 5000
          expire: 1000*60*5
      - search: (^4|^5) 
        searchin: status 
        action: return
        return:
          body: 呐呐呐！欧尼酱！！！这个页面挂掉了呢！！！（＞人＜；）请联系网站管理员哦！！
          status: 503
